customhost = "hr-database.corvssd1k2vi.us-east-1.rds.amazonaws.com"
customuser = "hr_user"
custompass = "hruser123"
customdb = "employee"
custombucket = "chongkahyee-bucket"
customregion = "us-east-1"
